### ISSUE TITLE
Crash upon opening

### ISSUE THREAD

**Issue by tinjaw** [alexanderwe/checksum-validator#26]
# Bug Report

## Your Environment

| Software           | Version(s) |
| ------------------ | ---------- |
| checksum-validator |    1.1.5        |
| Operating System   |    Mac OS X 10.14 (18A391)        |

## Expected Behavior

It opens w/o crashing.

## Current Behavior

It crashes on opening.

[ChecksumValidatorCrashReport.txt](https://github.com/alexanderwe/checksum-validator/files/2522087/ChecksumValidatorCrashReport.txt)

**Comment by alexanderwe** [comment]
Hey @tinjaw, thanks for submitting the issue. You are correct, the current version 1.1.5 crashes due to the update to MacOS Mojave. I released a new version which you can find here: https://github.com/alexanderwe/checksum-validator/releases/tag/v1.1.6

Due to the application not starting because of this error, I would like to ask you to download the new release from the releases section. Can you then please confirm the new version is working for you ? 

I tested it on Mojave on my machine and everything is working so far.

**Comment by tinjaw** [comment]
Thanks. I downloaded and installed the update. It fired up without any errors. I'll report any errors in a new issue if anything pops up. Thank you.

**Comment by alexanderwe** [comment]
Thanks a lot for your response. I am glad that the update resolved your issue.
